// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4cv7R89KTbIcXlbL6HWafTE8rBuyDt8',
    appId: '1:242777030865:web:14e42e174420588e8645f0',
    messagingSenderId: '242777030865',
    projectId: 'pizzabrosa-e6884',
    authDomain: 'pizzabrosa-e6884.firebaseapp.com',
    storageBucket: 'pizzabrosa-e6884.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0Mw0tDRo3UgkDWOFcrJD_-4ZN9TNmyA',
    appId: '1:242777030865:android:8c2a8b0c3a35b0078645f0',
    messagingSenderId: '242777030865',
    projectId: 'pizzabrosa-e6884',
    storageBucket: 'pizzabrosa-e6884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_-KMLXnnIZQG_whA43QgKsbqc1SKqLk',
    appId: '1:242777030865:ios:d83fe08f01daa1d28645f0',
    messagingSenderId: '242777030865',
    projectId: 'pizzabrosa-e6884',
    storageBucket: 'pizzabrosa-e6884.firebasestorage.app',
    iosBundleId: 'com.example.pizzeriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_-KMLXnnIZQG_whA43QgKsbqc1SKqLk',
    appId: '1:242777030865:ios:d83fe08f01daa1d28645f0',
    messagingSenderId: '242777030865',
    projectId: 'pizzabrosa-e6884',
    storageBucket: 'pizzabrosa-e6884.firebasestorage.app',
    iosBundleId: 'com.example.pizzeriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4cv7R89KTbIcXlbL6HWafTE8rBuyDt8',
    appId: '1:242777030865:web:5b497822910d30858645f0',
    messagingSenderId: '242777030865',
    projectId: 'pizzabrosa-e6884',
    authDomain: 'pizzabrosa-e6884.firebaseapp.com',
    storageBucket: 'pizzabrosa-e6884.firebasestorage.app',
  );
}